const $=id=>document.getElementById(id);let auth='',busy=false,lastHistory=0,lastLive=null;
const time=value=>{if(!value)return NaN;return Date.parse(/[zZ]$|[+-]\d\d:\d\d$/.test(value)?value:value+'Z')};
const clock=t=>new Date(t).toLocaleString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e}
function age(row){const t=time(row?.timestamp);if(!Number.isFinite(t))return 'Timestamp unavailable';const m=Math.floor((Date.now()-t)/60000);return m<0?'Timestamp ahead of clock':m<1?'Just reported':`${m} min ago`}
function isStale(row){const t=time(row?.timestamp);return !Number.isFinite(t)||Date.now()-t>300000||t-Date.now()>60000}
function reading(row){return row&&typeof row.value==='number'&&Number.isFinite(row.value)?`${row.value.toLocaleString('en-US',{maximumFractionDigits:2})} ${row.suffix||''}`:'No recent data'}
function renderLive(payload){lastLive=payload;const rows=new Map(payload.data.sensorData.map(s=>[s.sensorId,s]));$('metrics').replaceChildren();for(const [id,name,group]of payload.sensors.filter(s=>s[2]==='climate')){const row=rows.get(id),card=el('article',undefined,'metric');card.append(el('span',name,'label'),el('strong',reading(row)),el('small',row?(isStale(row)?'Stale · ':'')+age(row):'Not reporting',row&&isStale(row)?'stale':''));applyTarget(card,name,row);$('metrics').append(card)}$('probes').replaceChildren();for(let probe=1;probe<=4;probe++){const tr=el('tr');tr.append(el('td',`Probe ${probe}`));for(const label of ['Moisture','Temperature','EC']){const spec=payload.sensors.find(s=>s[2]===probe&&s[1]===label),row=spec&&rows.get(spec[0]),td=el('td',reading(row));if(row)td.append(el('small',(isStale(row)?'Stale · ':'')+age(row),isStale(row)?'stale':''));tr.append(td)}$('probes').append(tr)}renderOperations(payload);$('updated').textContent=`Last fetched ${clock(time(payload.fetchedAt))} · Refreshes every 30 seconds · Sensor times interpreted as UTC.`}
const ns='http://www.w3.org/2000/svg';function svgNode(tag,attrs,text){const e=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;return e}
function renderHistory(payload,target='charts'){const container=$(target);container.replaceChildren();const colors=['#b4e893','#7dc9ed','#e4b4ff'];const selected=payload.data.series.filter(s=>[1,2,8,10,12,14,15].includes(s.seriesType));selected.forEach((series,i)=>{const points=(series.data||[]).filter(p=>Number.isFinite(time(p.x))&&typeof p.y==='number'&&Number.isFinite(p.y)).sort((a,b)=>time(a.x)-time(b.x));const wrap=el('div',undefined,'chart');wrap.append(el('h3',`${series.name} · ${(series.unit||'').trim()}`));if(!points.length){wrap.append(el('p','No recorded data'));container.append(wrap);return}const values=points.map(p=>p.y),low=Math.min(...values),high=Math.max(...values),pad=Math.max((high-low)*.12,.1),min=low-pad,max=high+pad;const start=payload.start?time(payload.start):time(points[0].x),end=payload.end?time(payload.end):time(points.at(-1).x),x=t=>60+((t-start)/Math.max(1,end-start))*1020,y=v=>155-((v-min)/(max-min))*135;const svg=svgNode('svg',{viewBox:'0 0 1100 190',role:'img','aria-label':`${series.name}, minimum ${low}, maximum ${high}`});const dn=(payload.data.dayNight||[]).filter(p=>Number.isFinite(time(p.x))).sort((a,b)=>time(a.x)-time(b.x));for(let n=0;n<dn.length;n++){const a=Math.max(start,time(dn[n].x)),b=Math.min(end,n+1<dn.length?time(dn[n+1].x):end);if(dn[n].y>0&&b>a)svg.append(svgNode('rect',{x:x(a),y:20,width:x(b)-x(a),height:135,fill:'#b4e893',opacity:'.055'}))}for(let n=0;n<4;n++){const v=min+(max-min)*n/3,yy=y(v);svg.append(svgNode('line',{x1:60,x2:1080,y1:yy,y2:yy,class:'grid'}),svgNode('text',{x:5,y:yy+4},v.toFixed(series.seriesType===14?2:1)))}let path='',previous=null;for(const p of points){const t=time(p.x);path+=(previous===null||t-previous>(target==='weatherCharts'?5400000:1800000)?'M':'L')+x(t).toFixed(2)+' '+y(p.y).toFixed(2)+' ';previous=t}svg.append(svgNode('path',{d:path,fill:'none',stroke:colors[i%3],'stroke-width':2.5,'vector-effect':'non-scaling-stroke'}),svgNode('text',{x:60,y:183},clock(start)),svgNode('text',{x:1080,y:183,'text-anchor':'end'},clock(end)));wrap.append(svg);addChartInspection(wrap,svg,points,series,x,y,start,end,colors[i%3]);container.append(wrap)});$(target==='charts'?'historyStatus':'weatherStatus').textContent=`Recorded history · Last ${$('range').value} hours · Min/max use returned data.`}
function nearestPoint(points,target){let lo=0,hi=points.length-1;while(lo<hi){const mid=Math.floor((lo+hi)/2);if(time(points[mid].x)<target)lo=mid+1;else hi=mid}if(lo>0&&Math.abs(time(points[lo-1].x)-target)<=Math.abs(time(points[lo].x)-target))lo--;return lo}
function addChartInspection(wrap,svg,points,series,x,y,start,end,color){
 const tooltip=el('div',undefined,'chart-tooltip');tooltip.hidden=true;tooltip.setAttribute('role','status');
 const value=el('strong'),stamp=el('span');tooltip.append(value,stamp);wrap.append(tooltip);
 const guide=svgNode('line',{y1:20,y2:155,stroke:color,'stroke-width':1,'stroke-dasharray':'4 4','pointer-events':'none',visibility:'hidden'});
 const marker=svgNode('circle',{r:4.5,fill:color,stroke:'#0c1411','stroke-width':2,'pointer-events':'none',visibility:'hidden'});svg.append(guide,marker);
 let index=0;svg.setAttribute('tabindex','0');svg.setAttribute('role','group');svg.setAttribute('aria-label',series.name+'. Move pointer or use left and right arrows to inspect recorded values.');
 function show(n){index=Math.max(0,Math.min(points.length-1,n));const p=points[index],px=x(time(p.x)),py=y(p.y);guide.setAttribute('x1',px);guide.setAttribute('x2',px);guide.setAttribute('visibility','visible');marker.setAttribute('cx',px);marker.setAttribute('cy',py);marker.setAttribute('visibility','visible');value.textContent=`${series.name}: ${p.y.toLocaleString('en-US',{maximumFractionDigits:2})} ${(series.unit||'').trim()}`;stamp.textContent=clock(time(p.x))+' ET';tooltip.hidden=false;
 const position=svg.createSVGPoint();position.x=px;position.y=py;const matrix=svg.getScreenCTM();if(!matrix)return;const screen=position.matrixTransform(matrix),rect=wrap.getBoundingClientRect();const width=tooltip.offsetWidth;tooltip.style.left=Math.max(0,Math.min(wrap.clientWidth-width,screen.x-rect.left+12))+'px';tooltip.style.top=Math.max(0,screen.y-rect.top-tooltip.offsetHeight-12)+'px';}
 function hide(){tooltip.hidden=true;guide.setAttribute('visibility','hidden');marker.setAttribute('visibility','hidden')}
 svg.addEventListener('pointermove',event=>{const matrix=svg.getScreenCTM();if(!matrix)return;const position=svg.createSVGPoint();position.x=event.clientX;position.y=event.clientY;const local=position.matrixTransform(matrix.inverse());if(local.x<60||local.x>1080||local.y<20||local.y>155){hide();return}const target=start+(local.x-60)/1020*(end-start);show(nearestPoint(points,target))});
 svg.addEventListener('pointerleave',hide);svg.addEventListener('focus',()=>show(index));svg.addEventListener('blur',hide);svg.addEventListener('keydown',event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();show(event.key==='Home'?0:event.key==='End'?points.length-1:index+(event.key==='ArrowLeft'?-1:1))}});
}
async function request(mode){const r=await fetch(`/api/data?mode=${mode}&hours=${$('range').value}`,{headers:{Authorization:auth},cache:'no-store'});const j=await r.json();if(!r.ok){const e=new Error(j.error||'Request failed');e.status=r.status;throw e}return j}
function error(e){$('status').textContent='Connection issue';$('message').textContent=e.message;$('connection').hidden=false;$('message').className='error';if(e.status===401){auth='';$('login').hidden=false}if(lastLive){$('updated').textContent='Connection interrupted. Displayed readings are from the last successful request.';for(const item of document.querySelectorAll('.metric small')){item.textContent='Connection interrupted';item.className='stale'}}}
async function refresh(forceHistory=false){if(busy||!auth)return;busy=true;$('refresh').disabled=true;try{renderLive(await request('live'));$('status').textContent='Connected · 30 sec refresh';$('connection').hidden=true;$('signout').hidden=false;if(forceHistory||Date.now()-lastHistory>300000){try{renderHistory(await request('history'));lastHistory=Date.now()}catch(e){$('historyStatus').textContent=e.message}try{const weather=await request('weather');renderHistory(weather,'weatherCharts');const points=weather.data.series[0].data;$('weatherStatus').textContent=points.length?`${weather.source} · ${points.length} observations · Latest ${clock(time(points.at(-1).x))} ET`:'No outside observations available for this range.'}catch(e){$('weatherCharts').replaceChildren();$('weatherStatus').textContent=e.message}}}catch(e){error(e)}finally{busy=false;$('refresh').disabled=false}}
$('login').onsubmit=e=>{e.preventDefault();const bytes=new TextEncoder().encode('farber:'+$('password').value);auth='Basic '+btoa(Array.from(bytes,b=>String.fromCharCode(b)).join(''));$('password').value='';refresh(true)};$('refresh').onclick=()=>refresh(true);$('range').onchange=()=>refresh(true);$('signout').onclick=()=>{auth='';lastLive=null;lastHistory=0;$('metrics').replaceChildren();$('probes').replaceChildren();$('charts').replaceChildren();clearOperations();$('weatherCharts').replaceChildren();$('weatherStatus').textContent='Connect to load observed outside temperatures.';$('connection').hidden=false;$('login').hidden=false;$('message').className='';$('message').textContent='Enter your dashboard password to load Growlink readings.';$('status').textContent='Locked';$('signout').hidden=true;$('updated').textContent='No live readings loaded.'};setInterval(()=>refresh(),30000);
fetch('/api/data?mode=live').then(async r=>{if(r.status===503){const j=await r.json();$('message').textContent=j.error}}).catch(()=>{$('message').textContent='Could not reach the dashboard backend. Try refreshing.'});

const defaults={flipDate:'2026-09-15',lightsPct:85,tTemp:82,tRh:60,tVpd:1.35,tPpfd:1000,tVwc:45,tEc:3};let cfg={...defaults};try{cfg={...defaults,...JSON.parse(localStorage.getItem('farberProfileV2')||'{}')}}catch{}
const targetMap={'Room temperature':['tTemp',2,'°F'],'Relative humidity':['tRh',4,'%'],'Growlink VPD':['tVpd',.18,'kPa'],'PPFD':['tPpfd',125,'µmol/m²/s']};
function applyTarget(card,name,row){const rule=targetMap[name];if(!rule)return;let status='Awaiting data';if(row&&!isStale(row)&&Number.isFinite(row.value)){const delta=row.value-cfg[rule[0]],distance=Math.abs(delta);status=distance<=rule[1]?'ON TARGET':delta>0?'HIGH':'LOW';card.classList.add(distance<=rule[1]?'good':distance<=rule[1]*2?'warn':'bad')}card.append(el('div',`Target ${cfg[rule[0]]} ${rule[2]} · ${status}`,'target'))}
function stat(parent,label,value,note){const box=el('div',undefined,'stat');box.append(el('small',label),el('strong',value));if(note)box.append(el('small',note));parent.append(box)}
function renderProfile(){const today=new Date().toLocaleDateString('en-CA',{timeZone:'America/New_York'});const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const get=t=>parts.find(p=>p.type===t).value;const nowDate=`${get('year')}-${get('month')}-${get('day')}`;const day=Math.floor((Date.parse(nowDate+'T00:00:00Z')-Date.parse(cfg.flipDate+'T00:00:00Z'))/86400000)+1;$('flowerDay').textContent=day>0?day:'Pre-flip';$('phase').textContent=day<=21?'EARLY FLOWER · STRETCH':day<=49?'MID FLOWER · BULK':'LATE FLOWER · RIPEN';$('lightTag').textContent=`Lights ${cfg.lightsPct}% · profile`;}
function renderOperations(payload){renderProfile();const rows=new Map(payload.data.sensorData.map(s=>[s.sensorId,s]));const get=(name,group='climate')=>{const spec=payload.sensors.find(s=>s[1]===name&&s[2]===group),r=spec&&rows.get(spec[0]);return r&&!isStale(r)&&Number.isFinite(r.value)?r.value:null};const t=get('Room temperature'),rh=get('Relative humidity'),vpd=get('Growlink VPD');let dp=null;if(t!==null&&rh!==null&&rh>0&&rh<=100){const c=(t-32)*5/9,a=Math.log(rh/100)+17.27*c/(237.7+c);dp=237.7*a/(17.27-a)*9/5+32}const format=(v,unit)=>v===null?'Not available':v.toFixed(1)+' '+unit;const hero=$('heroStats');hero.replaceChildren();stat(hero,'AIR VPD',format(vpd,'kPa'));stat(hero,'DEW POINT',format(dp,'°F'));stat(hero,'LEAF ΔT','Not connected','No leaf sensor mapped');stat(hero,'HUMIDITY WATCH',rh===null?'Awaiting data':rh>=68?'HIGH':rh>=64?'WATCH':'IN BAND','Simple RH flag');const alerts=$('alerts');alerts.replaceChildren();const flag=(title,body,cls='')=>{const box=el('div',undefined,'alert '+cls);box.append(el('strong',title),el('span',body));alerts.append(box)};if(rh===null)flag('Humidity unavailable','Fresh room data is required.');else if(rh>=64)flag(rh>=68?'High humidity':'Humidity watch',`Room RH ${rh.toFixed(1)}%.` ,rh>=68?'bad':'warn');if(vpd!==null&&Math.abs(vpd-cfg.tVpd)>.35)flag('VPD drift',`Air VPD differs from the ${cfg.tVpd} kPa reference target.`,'warn');if(dp!==null)flag('Dew-point reference',`Surfaces at or below ${dp.toFixed(1)}°F could collect condensation.`);for(let n=1;n<=4;n++){const m=get('Moisture',n);if(m!==null&&m<cfg.tVwc-10)flag(`Probe ${n} moisture low`,`${m.toFixed(1)}% versus ${cfg.tVwc}% reference. Verify probe placement and irrigation.`,'warn')}if(!alerts.children.length)flag('No threshold flags','Fresh readings are within dashboard reference bands.');const root=$('rootSummary');root.replaceChildren();const avg=name=>{const values=[1,2,3,4].map(n=>get(name,n)).filter(v=>v!==null);return values.length?values.reduce((a,b)=>a+b,0)/values.length:null};const m=avg('Moisture'),ec=avg('EC'),st=avg('Temperature');stat(root,'AVG MOISTURE',format(m,'%'),`Reference ${cfg.tVwc}% · reporting probes`);stat(root,'AVG ROOT EC',format(ec,'EC'),`Reference ${cfg.tEc} EC`);stat(root,'ROOT / AIR ΔT',format(st===null||t===null?null:st-t,'°F'),'Reporting-probe average');}
function clearOperations(){for(const id of ['heroStats','rootSummary'])$(id).replaceChildren();$('alerts').textContent='Connect to evaluate readings.'}
function setupProfile(){renderProfile();const fields=[['flipDate','Flower flip date','date'],['lightsPct','Light power profile (%)','number'],['tTemp','Air temperature target (°F)','number'],['tRh','RH target (%)','number'],['tVpd','VPD target (kPa)','number'],['tPpfd','PPFD target (µmol/m²/s)','number'],['tVwc','Moisture reference (%)','number'],['tEc','Root EC reference','number']];for(const[key,label,type]of fields){const l=el('label',label),input=el('input');input.name=key;input.type=type;input.value=cfg[key];input.required=true;if(type==='number'){input.step='any';input.min=key==='tTemp'?'32':'0';input.max=['lightsPct','tRh','tVwc'].includes(key)?'100':'2000'}l.append(input);$('fields').append(l)}$('settingsBtn').onclick=()=>$('settings').hidden=!$('settings').hidden;$('settingsForm').onsubmit=e=>{e.preventDefault();for(const[key,,type]of fields)cfg[key]=type==='number'?Number(e.target.elements[key].value):e.target.elements[key].value;try{localStorage.setItem('farberProfileV2',JSON.stringify(cfg))}catch{}renderProfile();if(lastLive)renderLive(lastLive);$('settings').hidden=true};for(const[name,description]of [['Fluence SPYDR 2i',`${cfg.lightsPct}% profile · 12/12`],['Quest DG12','Compressor / fan telemetry'],['Can fans / HAF','Ventilation and circulation'],['Growlink PIC','Root-zone sensors mapped'],['CO₂','No sensor mapped']]){const row=el('div',undefined,'system-row'),text=el('div',name);text.append(el('small',description));row.append(text,el('span','Status unavailable','badge'));$('systems').append(row)}}
setupProfile();
